<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by shp2Cgml v.1.1, a tool developed by Alexander Simons                         at European Institute for Energy Redsearch Karlsruhe with modificated                         script parts of Random3Dcity (http://github.com/tudelft3d/Random3Dcity),                         a tool developed by Filip Biljecki at TU Delft. Version: 2015-10-05. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:gml="http://www.opengis.net/gml" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <gml:name>Prototype</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:4326">
      <gml:lowerCorner>3448103.6159 5422829.6355 0</gml:lowerCorner>
      <gml:upperCorner>3465238.5044 5437351.9016 69</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="33905475">
      <bldg:boundedBy>
        <bldg:GroundSurface gml:id="surfaceIDb99d0dbf-2d5a-4223-8a7e-88aa5b44a883">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID9f5fb554-f28f-42ea-984b-971f3351dd8b" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID3102db03-9432-46b7-babb-6ca46537ad7f">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID2b7a03a9-0e10-4539-8ae6-eb9952d43603">
                      <gml:posList>3459524.7019 5432217.5877 0 3459531.1848 5432245.0217 0 3459557.8159 5432238.2767 0 3459550.7459 5432210.5467 0 3459524.7019 5432217.5877 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDa369195e-16a2-489a-9d9c-0690ee3e9fe8">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDe10fd731-91c6-43e1-80ac-46702bd078a4" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID757263e6-2e1b-4490-9b77-25247aa44a4e">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID966852a0-8728-49b0-bd9a-39fae845ed4c">
                      <gml:posList>3459531.1848 5432245.0217 0 3459524.7019 5432217.5877 0 3459524.7019 5432217.5877 9 3459531.1848 5432245.0217 9 3459531.1848 5432245.0217 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDfb588cb1-c3e2-493b-b67d-7f0eaa1501f1">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDc33a2a0e-7c74-425e-b66f-41766f63913c" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID32ec8384-0afe-43ab-8c32-7a727214ea5b">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID676cc39f-bcc5-4510-bee2-09472c879f1b">
                      <gml:posList>3459557.8159 5432238.2767 0 3459531.1848 5432245.0217 0 3459531.1848 5432245.0217 9 3459557.8159 5432238.2767 9 3459557.8159 5432238.2767 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID7ecf08a0-0537-4db7-9080-59a2df338990">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID93847e32-83db-4a74-aba6-9724d01014b9" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID811431de-37e5-437f-ba38-5bec6833d7be">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID43f90532-2551-4ae2-acb8-875cc7d053a8">
                      <gml:posList>3459550.7459 5432210.5467 0 3459557.8159 5432238.2767 0 3459557.8159 5432238.2767 9 3459550.7459 5432210.5467 9 3459550.7459 5432210.5467 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID66af00df-d51e-438b-a9ae-a0b05d384a07">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb9839d6a-951f-446e-806a-d3f0e71e7bcf" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID205f821a-fc8e-4528-ae68-134812bdda76">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID835cb436-7760-49bd-aa45-49dc5c6aa334">
                      <gml:posList>3459524.7019 5432217.5877 0 3459550.7459 5432210.5467 0 3459550.7459 5432210.5467 9 3459524.7019 5432217.5877 9 3459524.7019 5432217.5877 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface gml:id="surfaceID678c68bd-df79-40b0-80bf-bc9803db87e6">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb923b4f5-c2c1-4bbd-bd4c-6c29d9623a15" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDd18faaa4-0773-46c9-ba7f-21364f6e6515">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID99a32789-735d-4ffb-9a86-ca0598367d17">
                      <gml:posList>3459524.7019 5432217.5877 9 3459550.7459 5432210.5467 9 3459557.8159 5432238.2767 9 3459531.1848 5432245.0217 9 3459524.7019 5432217.5877 9</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="33905509">
      <bldg:boundedBy>
        <bldg:GroundSurface gml:id="surfaceIDee8d5a29-a67b-494b-abb1-fb20b3d0a641">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDc8ebbf9a-ec56-4d03-b751-cc9d72408f76" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID5e5e52f7-a2e2-4915-bb67-cbd7e570e282">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID3d8375b6-3712-4077-9a08-16d5707fbbe5">
                      <gml:posList>3459474.8046 5432186.167 0 3459478.7537 5432185.115 0 3459536.698 5432169.722 0 3459532.9049 5432155.0803 0 3459526.5091 5432156.5951 0 3459525.6341 5432151.9527 0 3459542.4466 5432122.6247 0 3459519.3989 5432106.3665 0 3459510.4103 5432122.4027 0 3459501.1601 5432124.6612 0 3459497.0082 5432125.9817 0 3459458.9408 5432136.1471 0 3459444.2095 5432126.9795 0 3459441.8547 5432130.0107 0 3459432.7779 5432124.9723 0 3459425.1477 5432137.7068 0 3459435.9467 5432143.2218 0 3459430.6074 5432152.1915 0 3459460.8121 5432169.9985 0 3459463.0473 5432179.6134 0 3459465.1692 5432188.7287 0 3459474.8046 5432186.167 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID068dc8c7-262a-4e3a-8440-4719fbae9ada">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID5a1d6f50-348f-4da0-8cb8-b60961b943f8" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID29e3ced3-7df4-489e-8ab6-a06b339c9c3b">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDaa55a81d-be0c-448b-ac8c-a8adb2b40992">
                      <gml:posList>3459478.7537 5432185.115 0 3459474.8046 5432186.167 0 3459474.8046 5432186.167 6 3459478.7537 5432185.115 6 3459478.7537 5432185.115 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDac27eb5c-3f75-43b2-8628-35cbcbb7320c">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDf678b409-bec9-4eae-8c20-77b848d9b79a" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDa2c44bc8-fb6a-45e1-b9c5-963b1b5a3909">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID9fa9167b-1ac9-4a18-a186-0ade18223c27">
                      <gml:posList>3459536.698 5432169.722 0 3459478.7537 5432185.115 0 3459478.7537 5432185.115 6 3459536.698 5432169.722 6 3459536.698 5432169.722 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID6a4fe0df-83b5-4fa7-a0d7-52773bc8a359">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDba8d0b91-12fd-496f-b715-f058cd1c1e13" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID76d90fc9-3d7b-456b-be4a-2fe0d76faff6">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID9f680282-df08-41d2-bd54-af92264a1ff5">
                      <gml:posList>3459532.9049 5432155.0803 0 3459536.698 5432169.722 0 3459536.698 5432169.722 6 3459532.9049 5432155.0803 6 3459532.9049 5432155.0803 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID47e2982f-741f-42c7-8a91-0f70306beede">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID8b12034b-07f2-4086-b89b-e8d0e92e9a28" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDa47010ea-1c20-4a6b-8f18-74c709326d2f">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDfd05b8e9-8e7a-4286-af97-0f66d30b2d61">
                      <gml:posList>3459526.5091 5432156.5951 0 3459532.9049 5432155.0803 0 3459532.9049 5432155.0803 6 3459526.5091 5432156.5951 6 3459526.5091 5432156.5951 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID5a497f66-f162-4f54-94d7-8e30f4fbfb81">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDccd2499e-9f15-4e1d-965d-e20e15510638" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID72013da2-ccf3-4ccd-994e-d9f02c960189">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDc0722284-3849-4515-8479-0dfd928adcd4">
                      <gml:posList>3459525.6341 5432151.9527 0 3459526.5091 5432156.5951 0 3459526.5091 5432156.5951 6 3459525.6341 5432151.9527 6 3459525.6341 5432151.9527 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID97ce5fe4-de85-4eb9-958c-77c5204882a2">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID152a67cc-6901-4039-ab20-c73bfff77a8d" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID0580d341-0944-4370-a6bb-45e4fa639d97">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID6946e2ea-71d8-40aa-9814-bc0813225b4b">
                      <gml:posList>3459542.4466 5432122.6247 0 3459525.6341 5432151.9527 0 3459525.6341 5432151.9527 6 3459542.4466 5432122.6247 6 3459542.4466 5432122.6247 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDf6854118-a315-4329-96af-78ec23cb342b">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID7fc7bcc2-2897-40c3-b043-c2a213be6996" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID3d3c0c1b-6054-4143-a597-d4afc3a3ea93">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID24eaccea-71cd-4384-8eda-c4e8f650c02b">
                      <gml:posList>3459519.3989 5432106.3665 0 3459542.4466 5432122.6247 0 3459542.4466 5432122.6247 6 3459519.3989 5432106.3665 6 3459519.3989 5432106.3665 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID9577c6ec-2eec-4824-9405-d59550171e95">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb3b47a64-57fa-4d61-92e6-6215af71625b" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID7de22a5c-616e-4d42-85c4-69f40fbfcd58">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDdfa2c559-9b8f-47df-bd63-48e3c1b8fe96">
                      <gml:posList>3459510.4103 5432122.4027 0 3459519.3989 5432106.3665 0 3459519.3989 5432106.3665 6 3459510.4103 5432122.4027 6 3459510.4103 5432122.4027 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDc3184564-29d0-4d7d-8cac-18b9e153858c">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb28ed550-5ef4-4232-a357-35b4c3323f10" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID42ebaa4d-a859-4feb-acc1-2f94fde6c515">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID0fc72352-3ff5-4ad9-b304-663168ae8d5a">
                      <gml:posList>3459501.1601 5432124.6612 0 3459510.4103 5432122.4027 0 3459510.4103 5432122.4027 6 3459501.1601 5432124.6612 6 3459501.1601 5432124.6612 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID21a7e92a-349a-4012-9ab7-267959b677e4">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID94f4976c-0730-467c-b704-88a7d9ccc495" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID973e8937-7e6c-41e5-ab5c-0b3c16cdacc2">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID75a3a700-2e72-40cc-b47c-d792b051adc9">
                      <gml:posList>3459497.0082 5432125.9817 0 3459501.1601 5432124.6612 0 3459501.1601 5432124.6612 6 3459497.0082 5432125.9817 6 3459497.0082 5432125.9817 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID98c3a08e-2a97-4829-9f3c-d3b24a1d6a24">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID0e620ee9-6239-46df-8ef3-0a31ccf9b9b4" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDaa272c9c-5ed9-4eae-8a0b-f5aa65414fdc">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID77533fe6-915c-4f24-a7f4-dfc8b5aac104">
                      <gml:posList>3459458.9408 5432136.1471 0 3459497.0082 5432125.9817 0 3459497.0082 5432125.9817 6 3459458.9408 5432136.1471 6 3459458.9408 5432136.1471 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID79e7878a-a8e4-4609-b832-ce94f1580fd8">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDf2d67bad-a8f1-48d6-a985-cbd227e2748e" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID3e8a7af8-91f1-496c-a6fe-f72c25843e83">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID33d3a242-8c54-4a7d-9288-90dfa275e279">
                      <gml:posList>3459444.2095 5432126.9795 0 3459458.9408 5432136.1471 0 3459458.9408 5432136.1471 6 3459444.2095 5432126.9795 6 3459444.2095 5432126.9795 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDa769d9c1-175a-4ed2-ab4c-c06ee2ebae50">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID9bfe92d9-ce59-4901-aefd-db297ee0726c" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID1cd05a2e-db97-4e1e-a6fc-b8307b7e16b8">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDb6494709-5443-4a78-8aa3-28ca521f54ca">
                      <gml:posList>3459441.8547 5432130.0107 0 3459444.2095 5432126.9795 0 3459444.2095 5432126.9795 6 3459441.8547 5432130.0107 6 3459441.8547 5432130.0107 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID220ff3c8-4b8b-42e7-b094-3f01ca18fa8a">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDeb7239c6-95ca-4bd3-b3eb-99276e2f1284" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDc649ef92-634a-414c-b736-20c7fb6ae0ce">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDf42b7795-971b-458a-9ee5-899bfd1ddb73">
                      <gml:posList>3459432.7779 5432124.9723 0 3459441.8547 5432130.0107 0 3459441.8547 5432130.0107 6 3459432.7779 5432124.9723 6 3459432.7779 5432124.9723 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDe1d155e1-d08b-4e83-bfdc-921e3f7becb7">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID81360103-56c1-453e-a96b-09ae51a4e1de" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID68c47ebd-dfe4-4185-83e3-adfca4ac96a3">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID6e3e0619-2afb-4f34-8f92-295ca3b77d48">
                      <gml:posList>3459425.1477 5432137.7068 0 3459432.7779 5432124.9723 0 3459432.7779 5432124.9723 6 3459425.1477 5432137.7068 6 3459425.1477 5432137.7068 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID98c7f7f1-ef76-4a8d-8e56-b9ed55e5a3cd">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDabf0668b-5ddd-444c-87b2-65c27d78acba" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID28ec6d37-857a-4321-af5d-19c7db62439c">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDdd6449f8-56c6-499d-abdd-88c90ca8f7d5">
                      <gml:posList>3459435.9467 5432143.2218 0 3459425.1477 5432137.7068 0 3459425.1477 5432137.7068 6 3459435.9467 5432143.2218 6 3459435.9467 5432143.2218 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDbcb1f0e0-bcc2-4563-b555-1dfba09e6bbf">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID00ef986a-5551-4d2f-9a38-a6dc1b730c02" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID764de2d7-49d3-4505-95e7-02e4baa5b881">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID5f885da6-8b08-44d3-9913-fa6e506802a5">
                      <gml:posList>3459430.6074 5432152.1915 0 3459435.9467 5432143.2218 0 3459435.9467 5432143.2218 6 3459430.6074 5432152.1915 6 3459430.6074 5432152.1915 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID522b46e3-1e5d-475a-960a-3d030672106f">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb75857a4-5e87-497d-96a1-1fc6a1341dfa" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDef31b35c-dfe7-4ec1-afd5-c35dbf67b699">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDf93091c5-5796-4f35-8322-0cd566f0532e">
                      <gml:posList>3459460.8121 5432169.9985 0 3459430.6074 5432152.1915 0 3459430.6074 5432152.1915 6 3459460.8121 5432169.9985 6 3459460.8121 5432169.9985 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID1ca6eeef-853a-417f-a4cf-2998e6e4e5ca">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID75733099-ad54-4482-b52b-2bf457815cec" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID669a9687-e116-43ec-b7f1-4f13487cbf66">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID7283296f-2b20-4e28-a5c2-6cc8b27218d7">
                      <gml:posList>3459463.0473 5432179.6134 0 3459460.8121 5432169.9985 0 3459460.8121 5432169.9985 6 3459463.0473 5432179.6134 6 3459463.0473 5432179.6134 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID3ed4f431-d46f-4948-be37-4b47d1f46658">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDd37cf1b1-8275-4bad-bb2b-f085ad60aef4" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID041f39a3-a06e-4181-a678-924048aea85b">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID5ebad757-dc2d-4279-82a7-ab5b2b311ef4">
                      <gml:posList>3459465.1692 5432188.7287 0 3459463.0473 5432179.6134 0 3459463.0473 5432179.6134 6 3459465.1692 5432188.7287 6 3459465.1692 5432188.7287 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID65ee6484-2d26-40cb-b18f-5e691e6ae2f4">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDcf72f177-056d-479d-b756-a48691d3fb31" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID617fe895-152c-42e3-b776-459ddf6a77ae">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDfbde66eb-6a48-43da-8b6b-f7f02169574d">
                      <gml:posList>3459474.8046 5432186.167 0 3459465.1692 5432188.7287 0 3459465.1692 5432188.7287 6 3459474.8046 5432186.167 6 3459474.8046 5432186.167 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface gml:id="surfaceID5f468531-fb13-4659-91e9-d331318d91e8">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDddb4e605-e327-4415-ad54-84f015515434" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID6e73b030-9108-43d5-9d1a-24cfe4025b00">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID3d39a685-8c7b-4624-a8e1-757e1ab8d637">
                      <gml:posList>3459474.8046 5432186.167 6 3459465.1692 5432188.7287 6 3459463.0473 5432179.6134 6 3459460.8121 5432169.9985 6 3459430.6074 5432152.1915 6 3459435.9467 5432143.2218 6 3459425.1477 5432137.7068 6 3459432.7779 5432124.9723 6 3459441.8547 5432130.0107 6 3459444.2095 5432126.9795 6 3459458.9408 5432136.1471 6 3459497.0082 5432125.9817 6 3459501.1601 5432124.6612 6 3459510.4103 5432122.4027 6 3459519.3989 5432106.3665 6 3459542.4466 5432122.6247 6 3459525.6341 5432151.9527 6 3459526.5091 5432156.5951 6 3459532.9049 5432155.0803 6 3459536.698 5432169.722 6 3459478.7537 5432185.115 6 3459474.8046 5432186.167 6</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
  <cityObjectMember>
    <bldg:Building gml:id="37943982">
      <bldg:boundedBy>
        <bldg:GroundSurface gml:id="surfaceID31a2ad8f-5ade-4f3c-8278-0aab98530a2d">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb6d249e9-f05b-4f5d-9603-bf79453a396f" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDfa13bffb-112d-4961-ba14-f36ea93d1d47">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID1a0b6ab0-a0c3-428f-8ddd-f16062288866">
                      <gml:posList>3460596.0508 5431500.5024 0 3460611.0027 5431493.4007 0 3460613.2823 5431498.1778 0 3460663.8535 5431474.1633 0 3460668.858 5431484.6487 0 3460742.2699 5431449.8073 0 3460739.9533 5431444.9413 0 3460805.9956 5431413.5895 0 3460788.347 5431376.6352 0 3460799.4356 5431371.3742 0 3460789.709 5431350.9905 0 3460748.2124 5431370.6913 0 3460751.1007 5431376.732 0 3460721.4292 5431390.8107 0 3460718.6226 5431384.9362 0 3460665.2653 5431410.2602 0 3460667.9976 5431415.9684 0 3460642.1101 5431428.2523 0 3460632.6134 5431408.3678 0 3460622.2758 5431413.2679 0 3460595.6376 5431425.9133 0 3460593.0834 5431420.5709 0 3460557.8648 5431437.2924 0 3460567.7924 5431458.0746 0 3460574.3171 5431454.9809 0 3460596.0508 5431500.5024 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDc3dc793a-cc5d-4c0a-a68d-2f24496e8969">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID4dab1027-8d36-4563-a2cd-98c4c073e1ec" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDab98802e-5b5d-40ce-80cb-fbdee8c852a0">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDe07104b6-b84c-45d1-99b0-b1f582921060">
                      <gml:posList>3460611.0027 5431493.4007 0 3460596.0508 5431500.5024 0 3460596.0508 5431500.5024 6 3460611.0027 5431493.4007 6 3460611.0027 5431493.4007 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID06ec96eb-f968-4165-9f2c-87f70658aad1">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID5cf11fd0-9fd8-43f0-a0ea-e0018c49f3ff" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID74a98792-cc88-41e5-81ff-8ac34ac99453">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID1ccef3fe-43b8-4705-a3e8-87baae0b353c">
                      <gml:posList>3460613.2823 5431498.1778 0 3460611.0027 5431493.4007 0 3460611.0027 5431493.4007 6 3460613.2823 5431498.1778 6 3460613.2823 5431498.1778 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDb95764f3-2ff5-458e-b9ac-492152d492c5">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDe99c7e2c-0b79-4f5f-b45d-35e2c1627f48" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID04587bc3-236a-4329-ab62-05b9877e6e24">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID6b08014e-565c-4cd6-b2b9-e91251547437">
                      <gml:posList>3460663.8535 5431474.1633 0 3460613.2823 5431498.1778 0 3460613.2823 5431498.1778 6 3460663.8535 5431474.1633 6 3460663.8535 5431474.1633 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID2ea29c78-b345-4d16-8e48-dc3749fb45f7">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID2fabaeb3-3e0b-4c73-a132-152ecd76b553" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID16d81994-3889-4b8b-9750-9574638cc7f7">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID3806f275-965e-4ef6-9091-54ffdf826314">
                      <gml:posList>3460668.858 5431484.6487 0 3460663.8535 5431474.1633 0 3460663.8535 5431474.1633 6 3460668.858 5431484.6487 6 3460668.858 5431484.6487 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID2f86f1f6-921d-43f1-9726-c0175cc3dec3">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDfe1bcaab-b438-475f-87da-c0845c82fca5" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDf49d1d83-7040-434e-a9f8-15aef4e7bfe5">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID9c669919-6402-48e5-b645-483525241047">
                      <gml:posList>3460742.2699 5431449.8073 0 3460668.858 5431484.6487 0 3460668.858 5431484.6487 6 3460742.2699 5431449.8073 6 3460742.2699 5431449.8073 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID31beb223-be34-4e8e-b92e-d1d6405cdfac">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDf0fe11d0-22f1-40f6-8e23-abdce4917add" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID0b5c9063-bbbc-4864-b751-94b1ff67845d">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID5b1aa6b8-5fd3-4790-94aa-24e5047850ff">
                      <gml:posList>3460739.9533 5431444.9413 0 3460742.2699 5431449.8073 0 3460742.2699 5431449.8073 6 3460739.9533 5431444.9413 6 3460739.9533 5431444.9413 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID3ee1b2a2-2707-4c69-8365-ef3cc57b5c90">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID60fca042-2033-43ed-bcc8-ae0f4e4c6190" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID85837fea-6af4-49c2-986f-c00a5f776818">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID0581d6cc-5873-4a9b-a674-6a1d55c7a00c">
                      <gml:posList>3460805.9956 5431413.5895 0 3460739.9533 5431444.9413 0 3460739.9533 5431444.9413 6 3460805.9956 5431413.5895 6 3460805.9956 5431413.5895 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID82cfa8d7-5046-406b-88f2-cc60b9df6158">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID286a1ff3-922f-4da4-89ff-7e50fed38fb6" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDd3506274-a97b-44f0-aa88-f5b691c39f48">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDcc29212d-46f0-4092-8217-53241a94ebdb">
                      <gml:posList>3460788.347 5431376.6352 0 3460805.9956 5431413.5895 0 3460805.9956 5431413.5895 6 3460788.347 5431376.6352 6 3460788.347 5431376.6352 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID8cb5c178-9e90-4149-bbce-f818b29306f4">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID386c793a-553c-4062-a9e0-227991f1da94" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID41e3d289-139c-40c1-81d2-f984a3573d7b">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID6d49fc44-5991-40a7-820a-fd6e287d59de">
                      <gml:posList>3460799.4356 5431371.3742 0 3460788.347 5431376.6352 0 3460788.347 5431376.6352 6 3460799.4356 5431371.3742 6 3460799.4356 5431371.3742 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID59833443-9a18-443e-ad10-bf560df219b7">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDc83fa039-1c07-4559-a5d7-4ccafd306f97" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID00ea98c8-859d-4770-bc34-b3bc7b300381">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID5cba0370-e368-46dd-bef5-176a63aa2f5a">
                      <gml:posList>3460789.709 5431350.9905 0 3460799.4356 5431371.3742 0 3460799.4356 5431371.3742 6 3460789.709 5431350.9905 6 3460789.709 5431350.9905 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID070172f8-d089-4bd9-8e62-285d03a8f27a">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDf65610fb-1bd7-4d9f-b272-d618008732ed" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDfe483608-390d-427a-935a-634868ce92ff">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID36398e1f-0aca-4b36-b240-bf060e820e36">
                      <gml:posList>3460748.2124 5431370.6913 0 3460789.709 5431350.9905 0 3460789.709 5431350.9905 6 3460748.2124 5431370.6913 6 3460748.2124 5431370.6913 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID3e1c9670-3dc2-4355-a2f4-62cabf945fa9">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID6cb7cfa5-f4b3-4eca-bcb0-7f164daaeeb5" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID888f4093-88e5-4659-836e-ea14d3f0bcda">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDedf0bbd5-f52b-4ef8-a160-a6c0b7a583d1">
                      <gml:posList>3460751.1007 5431376.732 0 3460748.2124 5431370.6913 0 3460748.2124 5431370.6913 6 3460751.1007 5431376.732 6 3460751.1007 5431376.732 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID18f3fab0-0a77-49c5-8efe-9978c702db05">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID5c2ced85-af5b-4518-abee-8591fb42e724" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID5ac51d23-7df9-410d-a1d4-c222f3e35e98">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID9be6a5bb-370d-486f-95fd-0a37c951466b">
                      <gml:posList>3460721.4292 5431390.8107 0 3460751.1007 5431376.732 0 3460751.1007 5431376.732 6 3460721.4292 5431390.8107 6 3460721.4292 5431390.8107 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDfed2e86b-5598-49e1-b72c-14a9ce2e9cfb">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID0c6bb50e-e909-49a9-87d5-2239931e05f4" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID90a01d40-e78d-4531-b337-c574a287066e">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID006b5703-440a-4bc3-a421-361a6057ce18">
                      <gml:posList>3460718.6226 5431384.9362 0 3460721.4292 5431390.8107 0 3460721.4292 5431390.8107 6 3460718.6226 5431384.9362 6 3460718.6226 5431384.9362 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID2b862090-4804-4bd4-81a5-0f754221a3c4">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb9aca2e3-c3e2-46d1-89fd-9897774043de" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID9d0499f6-fc8b-4202-8179-853c7d34c796">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID66a8d6aa-9553-40c4-9235-120ae48232ec">
                      <gml:posList>3460665.2653 5431410.2602 0 3460718.6226 5431384.9362 0 3460718.6226 5431384.9362 6 3460665.2653 5431410.2602 6 3460665.2653 5431410.2602 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDd191125d-5e51-4f42-b58b-4101881ec0d5">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID3cdb5021-7f48-4525-bdbd-2599717c12f7" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID7704044b-5b54-4e94-b657-794d1eda4e6b">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDc0f8cf80-b06c-478c-b5de-1245eb93f781">
                      <gml:posList>3460667.9976 5431415.9684 0 3460665.2653 5431410.2602 0 3460665.2653 5431410.2602 6 3460667.9976 5431415.9684 6 3460667.9976 5431415.9684 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID0a291c66-16c5-47af-ad18-806037f5e780">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID872202fb-f0b0-4f09-b06f-bd43b8b4e5b9" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID3d66c1fe-bce5-4319-9a58-aeb5a3844150">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDf0417377-840c-49dc-82ac-bb387481f221">
                      <gml:posList>3460642.1101 5431428.2523 0 3460667.9976 5431415.9684 0 3460667.9976 5431415.9684 6 3460642.1101 5431428.2523 6 3460642.1101 5431428.2523 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID2991ad5c-4a09-4d51-8ab0-2e03703b9c81">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb50d51a7-57d3-49a2-93a4-2e30c4043a19" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID1df479d4-e9bb-4fd4-9bc6-d8dc4650cf4b">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID07922894-4d50-457c-b31e-397d475c9de0">
                      <gml:posList>3460632.6134 5431408.3678 0 3460642.1101 5431428.2523 0 3460642.1101 5431428.2523 6 3460632.6134 5431408.3678 6 3460632.6134 5431408.3678 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID3d75e5d2-dba4-4ccf-9e78-91ef061ba576">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDfd65ee04-651b-4d19-987e-4cabfd2d1d90" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID34d19b2e-2444-44ed-b7ac-0a426511d95d">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDa7c07d55-ada6-454a-a066-0cca61a58c46">
                      <gml:posList>3460622.2758 5431413.2679 0 3460632.6134 5431408.3678 0 3460632.6134 5431408.3678 6 3460622.2758 5431413.2679 6 3460622.2758 5431413.2679 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID6dca662b-49a3-49f6-8c6e-b82896ede05f">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID5ca7bb8c-fc1f-4e2b-b050-76a0bf9e9281" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDf40ddaf9-a974-45c3-a182-fa511b1a71fe">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID861969ca-0348-4f52-980f-6532a56d6f12">
                      <gml:posList>3460595.6376 5431425.9133 0 3460622.2758 5431413.2679 0 3460622.2758 5431413.2679 6 3460595.6376 5431425.9133 6 3460595.6376 5431425.9133 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID508a00a0-2c05-469b-8858-14ef7072bc05">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDcf1a0a70-bda3-4903-9920-52a5de58babf" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID7281458a-44bf-4b7a-bb5b-40a8a010a0c3">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID1326d33d-068d-45cc-bb74-2b24abe132cc">
                      <gml:posList>3460593.0834 5431420.5709 0 3460595.6376 5431425.9133 0 3460595.6376 5431425.9133 6 3460593.0834 5431420.5709 6 3460593.0834 5431420.5709 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID925891be-8e3b-4bca-8c56-e2cf5ec11275">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID3a051bb2-92a5-4f3f-a9c0-bd59e2c48735" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID25553c42-d27b-4308-a066-fa9366961c64">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID1dd48e12-9401-4b8f-8291-cfb9ea3f2add">
                      <gml:posList>3460557.8648 5431437.2924 0 3460593.0834 5431420.5709 0 3460593.0834 5431420.5709 6 3460557.8648 5431437.2924 6 3460557.8648 5431437.2924 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDf22063ef-92a0-4e6c-b518-3ced79716da8">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDeeda1f46-9a6b-4670-ad1f-1d31668515bc" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDb2cd77e1-7b28-4a76-a82f-9b6e3c3422b0">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID68d12109-1cbd-4043-80d9-5bfd1c87b671">
                      <gml:posList>3460567.7924 5431458.0746 0 3460557.8648 5431437.2924 0 3460557.8648 5431437.2924 6 3460567.7924 5431458.0746 6 3460567.7924 5431458.0746 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID1fa8344d-e5a6-4ddb-954e-3865bcb1fc3a">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID8c538386-708b-403b-bf6d-62190c39f143" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDcb7652d0-cab1-4950-b3ec-a9f90405a4c1">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDd44501f2-c61e-425b-bf93-756a08978998">
                      <gml:posList>3460574.3171 5431454.9809 0 3460567.7924 5431458.0746 0 3460567.7924 5431458.0746 6 3460574.3171 5431454.9809 6 3460574.3171 5431454.9809 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID02f1f770-6b40-4644-b3bb-3585fea9d32e">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID76d37ec7-67ff-4b15-8597-980863850ed4" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDcf96141c-e407-4ab6-8cb5-01cf1fa60689">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID5a6b71b0-0b44-4919-84bb-60c1183194ef">
                      <gml:posList>3460596.0508 5431500.5024 0 3460574.3171 5431454.9809 0 3460574.3171 5431454.9809 6 3460596.0508 5431500.5024 6 3460596.0508 5431500.5024 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface gml:id="surfaceID57178c69-1880-416b-9929-a7836fa3ebf8">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDb4bbab9f-4b16-4eaa-bf1b-cf5f9eb839a3" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID7c594eec-1d46-495f-9d51-6f8ea7866600">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID41215360-3248-45bd-ba77-82a33bab7d03">
                      <gml:posList>3460596.0508 5431500.5024 6 3460574.3171 5431454.9809 6 3460567.7924 5431458.0746 6 3460557.8648 5431437.2924 6 3460593.0834 5431420.5709 6 3460595.6376 5431425.9133 6 3460622.2758 5431413.2679 6 3460632.6134 5431408.3678 6 3460642.1101 5431428.2523 6 3460667.9976 5431415.9684 6 3460665.2653 5431410.2602 6 3460718.6226 5431384.9362 6 3460721.4292 5431390.8107 6 3460751.1007 5431376.732 6 3460748.2124 5431370.6913 6 3460789.709 5431350.9905 6 3460799.4356 5431371.3742 6 3460788.347 5431376.6352 6 3460805.9956 5431413.5895 6 3460739.9533 5431444.9413 6 3460742.2699 5431449.8073 6 3460668.858 5431484.6487 6 3460663.8535 5431474.1633 6 3460613.2823 5431498.1778 6 3460611.0027 5431493.4007 6 3460596.0508 5431500.5024 6</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
