<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by shp2Cgml v.1.1, a tool developed by Alexander Simons                         at European Institute for Energy Research Karlsruhe with modificated                         script parts of Random3Dcity (http://github.com/tudelft3d/Random3Dcity),                         a tool developed by Filip Biljecki at TU Delft. Version: 2015-10-05. -->
<CityModel xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:gml="http://www.opengis.net/gml" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <gml:name>Prototype</gml:name>
  <gml:boundedBy>
    <gml:Envelope srsDimension="3" srsName="EPSG:4326">
      <gml:lowerCorner>8.38890662976141 49.0144681201561 0</gml:lowerCorner>
      <gml:upperCorner>8.39784082611284 49.0173185407483 21</gml:upperCorner>
    </gml:Envelope>
  </gml:boundedBy>
  <cityObjectMember>
    <bldg:Building gml:id="28245343">
      <bldg:boundedBy>
        <bldg:GroundSurface gml:id="surfaceIDe2aa1011-7d27-4ca0-bfd4-49e277e5c938">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID46e75f5c-4941-4ef0-a118-4bb801694983" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID65b74673-ee57-47c9-81c0-65da08d951bd">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID546d948a-a564-4104-b1f8-f732cdcb5551">
                      <gml:posList>8.39129764548042 49.017310640622 0 8.39127324263976 49.0170043408285 0 8.39160784296571 49.0169916390949 0 8.39193364263876 49.0169796382004 0 8.39191084035123 49.0167138381563 0 8.3911416407624 49.0167422411184 0 8.39089844177514 49.0167512422192 0 8.39092134395787 49.0170170420961 0 8.3910442436522 49.0170121410999 0 8.39106864524144 49.0173185407483 0 8.39129764548042 49.017310640622 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:GroundSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDabf04034-c768-4db1-bc77-5f4d5d1990ce">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID427a62ba-e656-4349-9fff-400a523f0b93" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID87022814-00dd-4888-b591-138ab0b5f502">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID828e2254-b616-4ce8-b78a-c32ecd0474f7">
                      <gml:posList>8.39127324263976 49.0170043408285 0 8.39129764548042 49.017310640622 0 8.39129764548042 49.017310640622 18 8.39127324263976 49.0170043408285 18 8.39127324263976 49.0170043408285 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID3f681e06-418c-4a17-8b8c-8939e7242d2f">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID5b75db3e-7ef3-42f5-9f47-06ae67efe279" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDbd574be0-eec8-4365-89d5-4c5df208e39a">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID5db456ed-706d-40fc-9364-9bd0bbc7519a">
                      <gml:posList>8.39160784296571 49.0169916390949 0 8.39127324263976 49.0170043408285 0 8.39127324263976 49.0170043408285 18 8.39160784296571 49.0169916390949 18 8.39160784296571 49.0169916390949 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID52784755-1b3a-4409-8d7a-7041aa761b07">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID869ce116-42d0-450e-8782-170dba7ce9f4" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID9a065765-ac4b-4fba-8cb7-040da51f3c0e">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID18f6cf7f-58b3-446f-a5b2-3453360796be">
                      <gml:posList>8.39193364263876 49.0169796382004 0 8.39160784296571 49.0169916390949 0 8.39160784296571 49.0169916390949 18 8.39193364263876 49.0169796382004 18 8.39193364263876 49.0169796382004 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID5606b7d9-2dce-4f36-92b5-604bcfc8afd5">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDc9a1b5a8-4bcd-4fe8-a3e2-50e01e2dd4e0" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDcf994f3b-f4be-4c35-8b5e-f37a7f304f97">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID56b132d3-8958-49a4-9a4a-a14f8f503ddd">
                      <gml:posList>8.39191084035123 49.0167138381563 0 8.39193364263876 49.0169796382004 0 8.39193364263876 49.0169796382004 18 8.39191084035123 49.0167138381563 18 8.39191084035123 49.0167138381563 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID5eea8602-7fe8-41d2-9d53-e02a23bb9f33">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID1e6e83d7-ab16-4bf7-b465-d3b157c29641" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID98e0744c-137a-4b57-ba68-ec26e9b60c48">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID0a4d03cb-09b7-4fff-b66b-d6873bd1bacd">
                      <gml:posList>8.3911416407624 49.0167422411184 0 8.39191084035123 49.0167138381563 0 8.39191084035123 49.0167138381563 18 8.3911416407624 49.0167422411184 18 8.3911416407624 49.0167422411184 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID902619dd-ebae-48e8-9a40-41da1faa8c9a">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID925dc370-20cf-43b6-9142-b4be065eed02" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDa1eaf5bf-ac7a-46cf-925b-f8181e224366">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDd471828b-f6fe-443b-89b4-28e305f27d06">
                      <gml:posList>8.39089844177514 49.0167512422192 0 8.3911416407624 49.0167422411184 0 8.3911416407624 49.0167422411184 18 8.39089844177514 49.0167512422192 18 8.39089844177514 49.0167512422192 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID4f0841c2-8035-4fdf-8210-61571559b833">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID050ed8c8-13dd-47a0-ab65-d5064eb4e5c6" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDb3e5561b-ec10-4dc1-9eed-236b03006ad9">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDd85b26f8-fac1-46bc-a450-73561689aac7">
                      <gml:posList>8.39092134395787 49.0170170420961 0 8.39089844177514 49.0167512422192 0 8.39089844177514 49.0167512422192 18 8.39092134395787 49.0170170420961 18 8.39092134395787 49.0170170420961 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceIDbedf7fc3-3712-4eae-9540-94bfc580e613">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID201d3eef-48a1-4a97-8cfb-5c295a70d91b" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyID5d8ef8ca-018b-4082-a970-74752ac010ac">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID4cc349a5-46ed-4d19-b345-cc1139eead26">
                      <gml:posList>8.3910442436522 49.0170121410999 0 8.39092134395787 49.0170170420961 0 8.39092134395787 49.0170170420961 18 8.3910442436522 49.0170121410999 18 8.3910442436522 49.0170121410999 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID3dff3735-908f-4ca1-9ee4-6ed033c1548b">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomIDd6cc64d5-b013-4a85-98ad-717d00b303af" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDb8e1545d-b9c1-435b-b0a8-ad7ca0d73e27">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID764b4455-c43b-4bd3-b275-2d8a71aa690f">
                      <gml:posList>8.39106864524144 49.0173185407483 0 8.3910442436522 49.0170121410999 0 8.3910442436522 49.0170121410999 18 8.39106864524144 49.0173185407483 18 8.39106864524144 49.0173185407483 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:WallSurface gml:id="surfaceID867d72a8-2d06-4dbb-9246-e9a2cb5f710b">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID1e6785dd-fbfd-4a8f-9071-977c0fd3d9be" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDdb840216-9728-46de-b0f5-4e2b200d61b4">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringIDcddd2c16-a26d-4c2f-acfe-59cd03faa9ba">
                      <gml:posList>8.39129764548042 49.017310640622 0 8.39106864524144 49.0173185407483 0 8.39106864524144 49.0173185407483 18 8.39129764548042 49.017310640622 18 8.39129764548042 49.017310640622 0</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:WallSurface>
      </bldg:boundedBy>
      <bldg:boundedBy>
        <bldg:RoofSurface gml:id="surfaceIDd8d22829-8574-4a5e-ae24-002fa09b7914">
          <bldg:lod2MultiSurface>
            <gml:MultiSurface gml:id="geomID3075798f-9137-4ac4-bfaf-eccf3666c2c9" gml:srsDimension="3">
              <gml:surfaceMember>
                <gml:Polygon gml:id="polyIDf534a6b1-a9d4-4192-b353-87e3842c61d2">
                  <gml:exterior>
                    <gml:LinearRing gml:id="ringID8cc91a39-1b3b-4611-8f93-5cf575b842e1">
                      <gml:posList>8.39129764548042 49.017310640622 18 8.39106864524144 49.0173185407483 18 8.3910442436522 49.0170121410999 18 8.39092134395787 49.0170170420961 18 8.39089844177514 49.0167512422192 18 8.3911416407624 49.0167422411184 18 8.39191084035123 49.0167138381563 18 8.39193364263876 49.0169796382004 18 8.39160784296571 49.0169916390949 18 8.39127324263976 49.0170043408285 18 8.39129764548042 49.017310640622 18</gml:posList>
                    </gml:LinearRing>
                  </gml:exterior>
                </gml:Polygon>
              </gml:surfaceMember>
            </gml:MultiSurface>
          </bldg:lod2MultiSurface>
        </bldg:RoofSurface>
      </bldg:boundedBy>
    </bldg:Building>
  </cityObjectMember>
</CityModel>
