"""
Converts the Yale Bright Star Catalogue (BSC5) into YaleBrightStars.hpp/.cpp, the stars G3M's StarsRenderer draws.

Input:  bsc5.json from https://github.com/brettonw/YaleBrightStarCatalog (MIT), a JSON
        conversion of BSC5 (Hoffleit & Warren 1991, http://tdc-www.harvard.edu/catalogs/bsc5.html)
Output: the stars as short arrays, 6 numbers per star (right ascension, declination, red, green, blue, magnitude),
        split in methods small enough for Java (64 KB of bytecode per method)

usage: python3 make_stars_cpp.py bsc5.json <G3M cpp folder>
"""
import json, math, os, re, sys

STARS_PER_METHOD = 1000  # 6000 shorts, under 64 KB of Java bytecode

def angleInDegrees(text, isRightAscension):
    numbers = [float(n) for n in re.findall(r"[\d.]+", text)]
    degrees = numbers[0] + numbers[1] / 60 + numbers[2] / 3600
    if isRightAscension:
        return degrees * 15  # hours to degrees
    return -degrees if text.strip().startswith("-") else degrees

# Ballesteros 2012, black body temperature from B-V
def temperature(bMinusV):
    return 4600 * (1 / (0.92 * bMinusV + 1.7) + 1 / (0.92 * bMinusV + 0.62))

# Tanner Helland's fit of the black body colour, 1000 K to 40000 K
def blackBodyColour(kelvin):
    t = min(max(kelvin, 1000), 40000) / 100
    red = 255 if t <= 66 else 329.698727446 * (t - 60) ** -0.1332047592
    green = 99.4708025861 * math.log(t) - 161.1195681661 if t <= 66 else 288.1221695283 * (t - 60) ** -0.0755148492
    blue = 255 if t >= 66 else (0 if t <= 19 else 138.5177312231 * math.log(t - 10) - 305.0447927307)
    colour = [min(max(c, 0), 255) / 255 for c in (red, green, blue)]
    brightest = max(colour)
    return [c / brightest for c in colour]

def encodedStars(inputPath):
    stars = [s for s in json.load(open(inputPath)) if "Vmag" in s and "RA" in s and "Dec" in s]
    magnitudes = [float(s["Vmag"]) for s in stars]
    result = []
    for star, magnitude in zip(stars, magnitudes):
        colour = blackBodyColour(temperature(float(star["B-V"]))) if "B-V" in star else [1, 1, 1]
        rightAscensionInTurns = angleInDegrees(star["RA"], True) / 360
        declinationInQuarterTurns = angleInDegrees(star["Dec"], False) / 90
        result.append([round(rightAscensionInTurns * 65536) % 65536 - 32768,
                       round(declinationInQuarterTurns * 32767)] +
                      [round(c * 255) for c in colour] +
                      [round(magnitude * 100)])
    print(f"{len(stars)} stars, magnitudes {min(magnitudes)} to {max(magnitudes)}")
    return result

HEADER = """//
//  YaleBrightStars.hpp
//  G3M
//
//  Generated by tools/stars/make_stars_cpp.py from the Yale Bright Star Catalogue (BSC5), don't edit.
//

#ifndef YaleBrightStars_hpp
#define YaleBrightStars_hpp

#include <stddef.h>

class IFloatBuffer;


class YaleBrightStars {
private:
  YaleBrightStars() {}

  static void putStar(IFloatBuffer* directions,
                      IFloatBuffer* colors,
                      size_t star,
                      short rightAscension,
                      short declination,
                      short red,
                      short green,
                      short blue,
                      short magnitude);

%(declarations)s

public:
  static size_t starsCount() {
    return %(starsCount)d;
  }

  // directions: 3 floats per star, unit vectors on the planet's cartesian axes (J2000, x towards right ascension 0h, z north)
  // colors: 4 floats per star, the hue at full brightness (red, green, blue) and the visual magnitude
  static void putStars(IFloatBuffer* directions,
                       IFloatBuffer* colors);

};

#endif
"""

SOURCE_HEAD = """//
//  YaleBrightStars.cpp
//  G3M
//
//  Generated by tools/stars/make_stars_cpp.py from the Yale Bright Star Catalogue (BSC5), don't edit.
//  Catalogue: Hoffleit & Warren 1991, http://tdc-www.harvard.edu/catalogs/bsc5.html
//

#include "YaleBrightStars.hpp"

#include "IFloatBuffer.hpp"
#include "IMathUtils.hpp"


// rightAscension in 1/65536 of a turn, shifted by half a turn to fit a short;
// declination in 1/32767 of a quarter turn; red, green and blue from 0 to 255; magnitude in hundredths
void YaleBrightStars::putStar(IFloatBuffer* directions,
                              IFloatBuffer* colors,
                              size_t star,
                              short rightAscension,
                              short declination,
                              short red,
                              short green,
                              short blue,
                              short magnitude) {
  const IMathUtils* mu = IMathUtils::instance();
  const double rightAscensionInRadians = (rightAscension + 32768) / 65536.0 * 2 * PI;
  const double declinationInRadians    = declination / 32767.0 * HALF_PI;
  const double cosDeclination = mu->cos(declinationInRadians);

  directions->put(star*3    , (float) (cosDeclination * mu->cos(rightAscensionInRadians)));
  directions->put(star*3 + 1, (float) (cosDeclination * mu->sin(rightAscensionInRadians)));
  directions->put(star*3 + 2, (float) mu->sin(declinationInRadians));

  colors->put(star*4    , red   / 255.0f);
  colors->put(star*4 + 1, green / 255.0f);
  colors->put(star*4 + 2, blue  / 255.0f);
  colors->put(star*4 + 3, magnitude / 100.0f);
}

void YaleBrightStars::putStars(IFloatBuffer* directions,
                               IFloatBuffer* colors) {
%(calls)s
}
"""

METHOD = """
void YaleBrightStars::putStars%(index)d(IFloatBuffer* directions,
%(indent)sIFloatBuffer* colors) {
  const short stars[] = {
%(rows)s
  };
  const size_t firstStar = %(firstStar)d;
  const size_t starsCount = %(starsCount)d;
  for (size_t i = 0; i < starsCount; i++) {
    const size_t s = i * 6;
    putStar(directions, colors, firstStar + i, stars[s], stars[s + 1], stars[s + 2], stars[s + 3], stars[s + 4], stars[s + 5]);
  }
}
"""

def main(inputPath, outputFolder):
    stars = encodedStars(inputPath)
    chunks = [stars[i:i + STARS_PER_METHOD] for i in range(0, len(stars), STARS_PER_METHOD)]
    declarations = "\n\n".join(f"  static void putStars{i}(IFloatBuffer* directions,\n{' ' * (23 + len(str(i)))}IFloatBuffer* colors);"
                               for i in range(len(chunks)))
    with open(os.path.join(outputFolder, "YaleBrightStars.hpp"), "w") as header:
        header.write(HEADER % {"declarations": declarations, "starsCount": len(stars)})
    calls = "\n".join(f"  putStars{i}(directions, colors);" for i in range(len(chunks)))
    source = SOURCE_HEAD % {"calls": calls}
    for i, chunk in enumerate(chunks):
        rows = ",\n".join("    " + ", ".join(str(n) for n in star) for star in chunk)
        source += METHOD % {"index": i, "indent": " " * (31 + len(str(i))), "rows": rows,
                            "firstStar": i * STARS_PER_METHOD, "starsCount": len(chunk)}
    with open(os.path.join(outputFolder, "YaleBrightStars.cpp"), "w") as output:
        output.write(source)

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
