//
//  YaleBrightStars.hpp
//  G3M
//
//  Generated by tools/stars/make_stars_cpp.py from the Yale Bright Star Catalogue (BSC5), don't edit.
//

#ifndef YaleBrightStars_hpp
#define YaleBrightStars_hpp

#include <stddef.h>

class IFloatBuffer;


class YaleBrightStars {
private:
  YaleBrightStars() {}

  static void putStar(IFloatBuffer* directions,
                      IFloatBuffer* colors,
                      size_t star,
                      short rightAscension,
                      short declination,
                      short red,
                      short green,
                      short blue);

  static void putStars0(IFloatBuffer* directions,
                        IFloatBuffer* colors);

  static void putStars1(IFloatBuffer* directions,
                        IFloatBuffer* colors);

  static void putStars2(IFloatBuffer* directions,
                        IFloatBuffer* colors);

  static void putStars3(IFloatBuffer* directions,
                        IFloatBuffer* colors);

  static void putStars4(IFloatBuffer* directions,
                        IFloatBuffer* colors);

  static void putStars5(IFloatBuffer* directions,
                        IFloatBuffer* colors);

  static void putStars6(IFloatBuffer* directions,
                        IFloatBuffer* colors);

  static void putStars7(IFloatBuffer* directions,
                        IFloatBuffer* colors);

public:
  static size_t starsCount() {
    return 9096;
  }

  // directions: 3 floats per star, unit vectors on the planet's cartesian axes (J2000, x towards right ascension 0h, z north)
  // colors: 4 floats per star, RGBA
  static void putStars(IFloatBuffer* directions,
                       IFloatBuffer* colors);

};

#endif
