#!/bin/sh

#  Script.sh
#  G3MiOSSDK
#
#  Created by Vidal Toboso on 25/11/14.
#


XCODEBUILD=/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

PROJECT=$(PROJECT_ROOT)/G3MiOSSDK.xcodeproj

# This is the name of the target within the Xcode project generated by the xcode project.
TARGET=G3MiOSSDK

SDKROOTDIR=/Users/Shared/_BUILDS_/G3MiOSSDK_SDK

echo "Start Universal "$TARGET" SDK Generation"

echo "Step 1 : "$TARGET" SDK Build Library for simulator and device architecture"

$XCODEBUILD -target "$TARGET" -sdk "iphonesimulator" -configuration "Release" clean build
$XCODEBUILD -target "$TARGET" -sdk "iphoneos" -configuration "Release" clean build

echo "Step 2 : Remove older SDK Directory"

rm -rf $SDKROOTDIR

echo "Step 3 : Create new SDK Directory Version"

mkdir $SDKROOTDIR
mkdir $SDKROOTDIR/build_SDK
mkdir $SDKROOTDIR/build_SDK/headers

echo "Step 4 : Create new SDK binary Version"

cp /Users/Shared/_BUILDS_/Release-iphoneos/libG3MiOSSDK.a $SDKROOTDIR/build_SDK
mv $SDKROOTDIR/build_SDK/libG3MiOSSDK.a $SDKROOTDIR/build_SDK/libG3MiOSSDK_device.a

cp /Users/Shared/_BUILDS_/Release-iphonesimulator/libG3MiOSSDK.a $SDKROOTDIR/build_SDK
mv $SDKROOTDIR/build_SDK/libG3MiOSSDK.a $SDKROOTDIR/build_SDK/libG3MiOSSDK_simulator.a

echo "Step 5 : Create combine lib files for various platforms into one"

# combine lib files for various platforms into one
lipo -create $SDKROOTDIR/build_SDK/libG3MiOSSDK_device.a $SDKROOTDIR/build_SDK/libG3MiOSSDK_simulator.a  -output $SDKROOTDIR/build_SDK/libG3MiOSSDK_SDK.a

echo "Step 6 : Copy headers Needed"
PROJECT_HOME=`pwd`
echo $PROJECT_HOME


cp $PROJECT_HOME/*.h $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Specific/*.h $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Specific/Derived/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Specific/GL/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Specific/Widget/*.h $SDKROOTDIR/build_SDK/headers

cp $PROJECT_HOME/Commons/Basic/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Cameras/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Downloader/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/GEO/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Geometry/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/GL/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Interfaces/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/JSON/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Layers/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Math/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Mesh/*.hpp $SDKROOTDIR/build_SDK/headers
cp $PROJECT_HOME/Commons/Rendererers/*.hpp $SDKROOTDIR/build_SDK/headers



echo "Step 7 : Copy other file needed like bundle"
cp -r $PROJECT_HOME/Classes/*.bundle $SDKROOTDIR/build_SDK/

echo "Step 8 : Create final SDK package"

rm -rf $SDKROOTDIR/G3MiOSSDK_SDK
mkdir $SDKROOTDIR/G3MiOSSDK_SDK
cp -r $SDKROOTDIR/build_SDK/headers $SDKROOTDIR/G3MiOSSDK_SDK
cp -r $SDKROOTDIR/build_SDK/*.bundle $SDKROOTDIR/G3MiOSSDK_SDK
cp  $SDKROOTDIR/build_SDK/libG3MiOSSDK_SDK.a $SDKROOTDIR/G3MiOSSDK_SDK

lipo -info $SDKROOTDIR/G3MiOSSDK_SDK/libG3MiOSSDK.a

echo "Finish Universal #TARGET_NAME# SDK Generation"

exit 0